name: Build and Publish Package

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  publish-package:
    if: ${{ github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/v') }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out sqlfmt main branch
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.2.2
      - name: Configure poetry
        run: poetry config --no-interaction pypi-token.pypi ${{ secrets.SQLFMT_PYPI_TOKEN }}
      - name: Get sqlfmt Version
        id: sqlfmt_version
        run: echo "sqlfmt_version=$(poetry version --short)" >> $GITHUB_OUTPUT
      - name: Build package
        run: poetry build --no-interaction
      - name: Publish package to PyPI
        run: poetry publish --no-interaction
      - name: Create a Github Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.sqlfmt_version.outputs.sqlfmt_version }}
          target_commitish: main
          token: ${{ secrets.SQLFMT_RELEASE_TOKEN }}
          body_path: CHANGELOG.md
          files: |
            LICENSE
            dist/*sqlfmt*.whl
            dist/*sqlfmt*.tar.gz
